<a href="https://colab.research.google.com/github/HendricoYehezky/Tugas-1/blob/main/Bab_2_3_Linear_Algebra_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Sebuah skalar direpresentasikan dengan sebuah tensor yang berisikan satu elemen saja ###
### Dalam skalar, kita dapat menggunakan operasi arimatika seperti penjumlahan, perkalian, pembagian atau eksponesialisasi ###
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [ ]:
### Vektor dapat dianggap sebagai sebuah daftar atas nilai-nilai skalar di dalamnya ###
### Nilai-nilai tersebut disebut juga sebagai entries atau komponen ###
### Contoh berikut adalah sebuah tensor satu dimensi yang memiliki empat elemen di dalamnya ###
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [ ]:
### Kita juga dapat mengakses elemen di dalam tensor tersebut dengan menyebut indeks di dalam tensor tersebut ###
x[3]

tensor(3)

In [ ]:
### Fungsi yang memanggil  panjang dimensi dan bentuk sebuah tensor ###
### Banyaknya data dalam tensor mewakili length dalam tensor ###
### Banyaknya sumbu di dalam tensor menyatakan dimensionality dalam tensor ###
print(len(x))
torch.Size([4])

4


torch.Size([4])

In [ ]:
### Dalam penyusunan nilai-nilai numerik di dalam sebuah matriks dengan ukuran m × n, kita dapat menginisiasikan sebuah tensor yang fungsinya dapat merepresentasikan sebagai sebuha matriks ###
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
### Fungsi Matriks Transpos ###
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [ ]:
### Fungsi yang mengecek apakah matriks A adalah simetris atau tidak (A = A.T) ###
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])