<a href="https://colab.research.google.com/github/HendricoYehezky/Tugas-1/blob/main/Bab_2_5_Automatic_Differentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
### Contoh diferensiasi Sederhana ###
from mxnet import autograd, np, npx

npx.set_np()

x = np.arange(4.0)
x

array([0., 1., 2., 3.])

In [5]:
# We allocate memory for a tensor's gradient by invoking `attach_grad`
x.attach_grad()
# After we calculate a gradient taken with respect to `x`, we will be able to
# access it via the `grad` attribute, whose values are initialized with 0s
x.grad

array([0., 0., 0., 0.])

In [6]:
# Place our code inside an `autograd.record` scope to build the computational
# graph
with autograd.record():
    y = 2 * np.dot(x, x)
y

array(28.)

In [7]:
y.backward()
x.grad

array([ 0.,  4.,  8., 12.])

In [8]:
x.grad == 4 * x

array([ True,  True,  True,  True])

In [9]:
with autograd.record():
    y = x.sum()
y.backward()
x.grad  # Overwritten by the newly calculated gradient

array([1., 1., 1., 1.])

In [10]:
### Backward untuk Variabel Non-Skalar ###
# When we invoke `backward` on a vector-valued variable `y` (function of `x`),
# a new scalar variable is created by summing the elements in `y`. Then the
# gradient of that scalar variable with respect to `x` is computed
with autograd.record():
    y = x * x  # `y` is a vector
y.backward()
x.grad  # Equals to y = sum(x * x)

array([0., 2., 4., 6.])

In [11]:
### Detaching Computation ###
with autograd.record():
    y = x * x
    u = y.detach()
    z = u * x
z.backward()
x.grad == u

array([ True,  True,  True,  True])

In [12]:
### Since the computation of y was recorded, we can subsequently invoke backpropagation on y to get the derivative of y = x * x with respect to x, which is 2 * x. ###
y.backward()
x.grad == 2 * x

array([ True,  True,  True,  True])

In [14]:
### Computing the Gradient of Python Control Flow ###
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [17]:
### Compute the Gradient ###
import torch
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

print(a)
print (d)

tensor(-2.1045, requires_grad=True)
tensor(-107748.1797, grad_fn=<MulBackward0>)


In [18]:
### melakukan verifikasi nilai tradien benar atau tidak ###
a.grad == d / a

tensor(True)