<a href="https://colab.research.google.com/github/HendricoYehezky/Tugas-1/blob/main/Bab_2_(Data_manipulation).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Untuk memulai platform PYTORCH, kita dapat memanggil modul torch ###
### Sebuah tensor merepresentasikan sebuah (multi dimensi) susunan dengan nilai-nilai numerik di dalamnya ####
### Sebuah susunan nilai-nilai numerik dengan satu sumbu atas sebuah tensor dapat disebut sebagai sebuah vektor ###
### Sebuah tensor yang memiliki dua sumbu disebut sebagai sebuah matriks ###
### Sebuah tensor yang memiliki sejumlah sumbu katakanlah k sumbu, maka dapat disebut sebagai tensor dengan orde-k ###
import torch

### Untuk membuat sebuah vektor dalam platform PYTORCH, kita dapat membuat susunan nilai-nilai numerik di dalanya yang dimulai dari 0 sampai dengan n###
x = torch.arange(12, dtype=torch.float32)
print (x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [ ]:
### Kita dapat mengecek ukuran sebuah tensor (panjang data atas tiap sumbu) dengan melakukan inspeksi properti bentuk (shape) sebuah tensor ###
x.shape

torch.Size([12])

In [ ]:
### Jika kita ingin mengetahui jumlah elemn di dalam sebuah tensor, yaitu hasil perkalian dari ukuran elemen-elemen didalamnya dengan perintah sebagai berikut ###
x.numel()

12

In [ ]:

### Untuk merubah bentuk dari sebuah tersor tanpa mengubah jumlah elemen-elemennya atau nilai-nilainya, kita dapat menggunakan modul berikut ini ####
X = x.reshape(3, 4)
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [ ]:
### Selanjutnya jika kita ingin menginisialisasikan matriks X di atas dengan mengganti input nilai numeriknya dengan nol, satu ataupun suatu konstanta, kita dapat menggunakan modul berikut ini ###
torch.zeros((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
### Seringkali, kita ingin menginput nilai -nilai numerik secara random atas elemen-elemen di dalam sebuah tensor dengan distribusi probabilitas tertentu ###
### Sebagai contoh, kita akan mengisi setiap elemen secara random terdistribusi normal ( mean = 0, dan sd =1) dalam tensor dengan ukuran 3  untuk keempat vektor di bawah ini###
torch.randn(3, 4)

tensor([[ 0.6808,  0.7565, -0.0263,  1.3932],
        [ 0.5714,  0.6415, -2.0569,  1.6451],
        [ 1.2170, -0.0326, -0.3462, -1.1795]])

In [ ]:
### Kita juga dapat membuat setiap elemen dalam tensor dalam bentuk tensor juga, yang ditunjukkan sbagai berikut ###
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])