<a href="https://colab.research.google.com/github/HendricoYehezky/Tugas-1/blob/main/Bab_2_1_Data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Untuk memulai platform PYTORCH, kita dapat memanggil modul torch ###
### Sebuah tensor merepresentasikan sebuah (multi dimensi) susunan dengan nilai-nilai numerik di dalamnya ####
### Sebuah susunan nilai-nilai numerik dengan satu sumbu atas sebuah tensor dapat disebut sebagai sebuah vektor ###
### Sebuah tensor yang memiliki dua sumbu disebut sebagai sebuah matriks ###
### Sebuah tensor yang memiliki sejumlah sumbu katakanlah k sumbu, maka dapat disebut sebagai tensor dengan orde-k ###
import torch

### Untuk membuat sebuah vektor dalam platform PYTORCH, kita dapat membuat susunan nilai-nilai numerik di dalanya yang dimulai dari 0 sampai dengan n###
x = torch.arange(12, dtype=torch.float32)
print (x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [ ]:
### Kita dapat mengecek ukuran sebuah tensor (panjang data atas tiap sumbu) dengan melakukan inspeksi properti bentuk (shape) sebuah tensor ###
x.shape

torch.Size([12])

In [ ]:
### Jika kita ingin mengetahui jumlah elemn di dalam sebuah tensor, yaitu hasil perkalian dari ukuran elemen-elemen didalamnya dengan perintah sebagai berikut ###
x.numel()

12

In [ ]:

### Untuk merubah bentuk dari sebuah tersor tanpa mengubah jumlah elemen-elemennya atau nilai-nilainya, kita dapat menggunakan modul berikut ini ####
X = x.reshape(3, 4)
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [ ]:
### Selanjutnya jika kita ingin menginisialisasikan matriks X di atas dengan mengganti input nilai numeriknya dengan nol, satu ataupun suatu konstanta, kita dapat menggunakan modul berikut ini ###
torch.zeros((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
### Seringkali, kita ingin menginput nilai -nilai numerik secara random atas elemen-elemen di dalam sebuah tensor dengan distribusi probabilitas tertentu ###
### Sebagai contoh, kita akan mengisi setiap elemen secara random terdistribusi normal ( mean = 0, dan sd =1) dalam tensor dengan ukuran 3  untuk keempat vektor di bawah ini###
torch.randn(3, 4)

tensor([[ 0.6808,  0.7565, -0.0263,  1.3932],
        [ 0.5714,  0.6415, -2.0569,  1.6451],
        [ 1.2170, -0.0326, -0.3462, -1.1795]])

In [ ]:
### Kita juga dapat membuat setiap elemen dalam tensor dalam bentuk tensor juga, yang ditunjukkan sbagai berikut ###
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [21]:
### Berikutnya juga terdapat operasi diantaranya ada operasi unary scalar dan binary scalar serta juga disertai operator aritmatika untuk melakukan operasi terhadap elemen-elemen didalamnya###
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y 

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [22]:
### Eksponensiasi juga dapat dimasukkan ke dalam kelompok operator unary ketika kita melakukan proses perkalian element-wise yaitu perkalian yang didapatkan dari penjumlahan antar elemen baris dengan elemen kolom yang bersesuaian ###
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [23]:
### Perkalian element-wise yang melibatkan perkalian dot produk ataupun perkalian matrisks juga dapat dibuat secara concatenate yaitu mengabungkan elemen-elemen setelah dilakukan proses perkalian menjadi sebuah matriks baru tentunya dapat ditunjukkan sebagai berikut ###
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [24]:
### Dalam kondisi tertentu, kita dapat menyusun susunan angka di dalam sebuah tensor ke dalam satu kolom atau satu baris ###
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [25]:
### karena dimensi tensor a dan b berbeda, maka bentuk mereka tidak akan dapat dibuat penjumlahannya, namun dalam operator penjumlahan di torch, program akan mengasumsikan kedua matriks tersebut dapat disesuaikan dimensinya dengan mereplikasikan kolom dan barisnya sehingga dapat dijumlahkan ###
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [26]:
### Dalam susunan array yang dikenal oleh bahasa program Python, kita dapat mengakses sebuah matriks atau tensor dengan menyebutkan komponen yang akan dipilih ###
### X[-1] mengartikan kita memilih elemen-elemen terakhir dalam sebuah matriks ###
### X[1:3] mengartikan kita memilih elemen-elemen kedua dan ketiga ###
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [27]:
### Sebelum program membaca datam kita dapat menuliskan data dalam matriksnya sesuai dengan indeks yang diberikan ###
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
### Dalam menjalankan operator terhadap data yang disimpan dalam memory, maka pada umumnya hasi operasi tersebut akan dialokasikan ke dalam memory yang baru ###
### Dalam pengecekan apakah hasil operator tersebut akan dialokasikan ke memory yang baru atau tidak, kita dapat mengeceknya dengan modul berikut ###
before = id(Y)
Y = Y + X
id(Y) == before

False

In [29]:
### Pengecekan tersebut sangat bermanfaat apabila kita mengaplikasikan pembelajaran mesin yang mungkin membutuhkan ratusan megabyte untuk mengenal parameter dan melakukan update dengan perkalian untuk setiap detiknya ###
### Sebagai ilustrasi, kita akan membuat sebuah matriks baru Z yang memiliki bentuk yang sama dengan matriks Y, dengan menggunakan zeros_like untuk mengalokasikan blok dengan entri 0 di dalamnya ####
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140681878780336
id(Z): 140681878780336


In [32]:
### Mengkonversi objek yang ada dalam python (Torch) yang dapat berupa tensor dalam torch atau array dalam numpy sehingga dapat memaksimalkan performa manipulasi data dengan baik ###
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [33]:
### Untuk mengubah sebuah tensor dengan ukuran 1 kedalam skalar, kita dapat menggunakan fungsi sebagai berikut ###
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)